/**
 * Chatterbox — Fortune System
 *
 * 200 fortunes total — 50 per vibe. CONTENT FINAL (v1.5, from FortunesM.W.D.csv).
 * Category names: Mystical, Funny, Wholesome, Dramatic ("Funny", never "Chaotic").
 * Do not edit fortune text without product owner (K.Melly) approval.
 */

const FORTUNES = {
  Mystical: [
    "The universe is rearranging a small miracle for you.",
    "A quiet star is guiding a loud dream.",
    "Your shadow knows a secret your heart is ready to hear.",
    "A hidden path reveals itself at twilight.",
    "The answer arrives when the question softens.",
    "Ancient winds are turning in your favor.",
    "The night sky is writing your next chapter.",
    "Something meant for you is already in motion.",
    "A distant light is closer than it appears.",
    "The river of time bends kindly toward you.",
    "The moon remembers what the daylight forgets.",
    "A sacred coincidence is approaching.",
    "The future sends its regards.",
    "A small wonder will change your perspective.",
    "The old magic still works.",
    "The stars applaud every brave beginning.",
    "A gentle force is opening a locked door.",
    "Your intuition is speaking in bold letters today.",
    "The sky is not finished with you yet.",
    "The answers live between moments.",
    "The horizon holds a gift wrapped in patience.",
    "An old dream is finding new roots.",
    "A mystery becomes a map.",
    "A forgotten wish is waking up.",
    "The cosmos rewards curious hearts.",
    "The next sign will find you when you stop searching.",
    "The moonlight favors your plans.",
    "An invisible thread is leading you somewhere meaningful.",
    "The universe enjoys surprising you.",
    "A forgotten blessing returns.",
    "The moon is collecting evidence in your favor.",
    "A meaningful encounter drifts closer.",
    "A quiet blessing is crossing your path.",
    "A door opens where none existed before.",
    "Your path and your purpose are becoming acquainted.",
    "The next chapter begins with trust.",
    "The next clue appears in plain sight.",
    "The universe enjoys a well-timed surprise.",
    "Fortune travels by unexpected roads.",
    "The universe loves a bold step.",
    "Your spirit recognizes an opportunity before your eyes do.",
    "The stars are keeping good company with your hopes.",
    "A spark of destiny hides in an ordinary day.",
    "The constellations approve of your direction.",
    "The stars have not lost track of you.",
    "The tide is carrying something valuable ashore.",
    "A celestial nudge arrives soon.",
    "Something ancient stirs on your behalf.",
    "The cosmic clock is striking the right hour.",
    "A whisper from the future reaches you today.",
  ],

  Funny: [
    "Your future is bright, but sunglasses remain optional.",
    "A nap counts as a strategy today.",
    "Someone will laugh at your joke. Eventually.",
    "You are one good snack away from greatness.",
    "Today rewards confidence, even when misplaced.",
    "Your Wi-Fi and your luck are both improving.",
    "The answer is yes. The question is questionable.",
    "A surprising amount of life can be solved with a sandwich.",
    "You have excellent taste in fortunes.",
    "A minor victory deserves a major celebration.",
    "Your next mistake will at least be memorable.",
    "Good news is circling overhead looking for parking.",
    "You will soon master something completely unnecessary.",
    "A lucky break is stretching before it arrives.",
    "Today is ideal for pretending you know what you're doing.",
    "The odds favor you, mostly because they're feeling generous.",
    "Your future self would like to thank you for finding your keys.",
    "Great things happen when you stop refreshing the page.",
    "Someone nearby is also winging it.",
    "A bold choice will save you three minutes.",
    "Your luck works best without supervision.",
    "The universe appreciates your commitment to snacks.",
    "Expect applause from at least one houseplant.",
    "The next shortcut will somehow take longer.",
    "You are remarkably qualified for today's nonsense.",
    "An unexpected compliment is headed your way.",
    "A good idea is hiding in plain sight.",
    "Today has strong \"it worked somehow\" energy.",
    "Your future includes fewer awkward moments than expected.",
    "The best part of your day may involve food.",
    "Your common sense is about to earn overtime pay.",
    "A small inconvenience is preparing a funny story.",
    "You are closer to success than your browser history suggests.",
    "A lucky coincidence forgot to cancel.",
    "Someone will appreciate your weirdness today.",
    "The universe is grading on a curve.",
    "Your charm remains surprisingly effective.",
    "An excellent opportunity arrives disguised as a regular Tuesday.",
    "You will soon discover why that happened. Maybe.",
    "The stars recommend lowering your expectations by 2%.",
    "Your next achievement comes with an unnecessary complication.",
    "A forgotten task may solve itself out of respect.",
    "Your luck just updated to the latest version.",
    "Today is perfect for being pleasantly surprised.",
    "A funny misunderstanding will have a happy ending.",
    "Your future remains highly compatible with dessert.",
    "Something you've been avoiding has become less scary.",
    "The universe supports your right to a second coffee.",
    "Everything is about to make slightly more sense.",
    "You are the correct amount of weird for this timeline.",
  ],

  Wholesome: [
    "Good things often arrive quietly.",
    "You are making more progress than you realize.",
    "The right people value your presence.",
    "Your effort is being noticed.",
    "Someone appreciates you more than they say.",
    "A gentle day can still be a meaningful one.",
    "A small kindness will travel farther than expected.",
    "Your smile changes more than your mood.",
    "Your kindness leaves a lasting impression.",
    "The future has room for your dreams.",
    "Small steps are still steps forward.",
    "The best version of today is enough.",
    "You have already survived difficult chapters.",
    "Something you planted is beginning to bloom.",
    "Your care for others matters.",
    "Something simple will make you happy today.",
    "Hope is doing quiet work behind the scenes.",
    "A simple joy is worth celebrating.",
    "A little patience will be rewarded.",
    "You deserve moments of ease.",
    "You carry more strength than you give yourself credit for.",
    "A good memory is being made right now.",
    "Today offers a fresh start.",
    "A peaceful answer is closer than it seems.",
    "Trust the progress you cannot yet measure.",
    "Your presence makes a difference.",
    "You are allowed to enjoy where you are.",
    "Good news often takes the scenic route.",
    "The people who love you are cheering for you.",
    "You are growing even on slow days.",
    "Someone will be glad to hear from you.",
    "A warm moment is on its way.",
    "A bright spot appears in an ordinary moment.",
    "Rest is part of the journey.",
    "A thoughtful gesture returns to you.",
    "The world is better with your contribution in it.",
    "There is beauty in today's ordinary moments.",
    "A kind word carries unexpected power.",
    "Your heart is stronger than your doubts.",
    "The next step does not need to be perfect.",
    "Peace arrives one moment at a time.",
    "You are exactly on time for your own story.",
    "The road ahead contains reasons to smile.",
    "A meaningful connection grows stronger.",
    "Good things are gathering quietly.",
    "Your persistence is creating opportunities.",
    "A pleasant surprise is finding its way to you.",
    "You are closer than you think.",
    "A calm solution is approaching.",
    "Your future self is grateful you kept going.",
  ],

  Dramatic: [
    "History may remember this as your intriguing era.",
    "A plot twist approaches with excellent timing.",
    "Today deserves a soundtrack.",
    "Your destiny has entered the chat.",
    "The spotlight is searching for you.",
    "The next chapter demands a dramatic entrance.",
    "Something magnificent refuses to stay postponed.",
    "The future is being unusually dramatic.",
    "Your next act has excellent reviews.",
    "The stars are preparing special effects.",
    "The universe enjoys your sense of timing.",
    "The main character energy is undeniable.",
    "The universe appreciates commitment to the bit.",
    "The curtain rises on a surprising opportunity.",
    "Your future is making bold promises.",
    "Your story is building toward a satisfying reveal.",
    "Something important is about to become obvious.",
    "Your rivals are imaginary but still concerned.",
    "The tension is almost worth it.",
    "Fortune admires persistence and flair.",
    "Your legend requires one more chapter.",
    "A turning point is rehearsing its entrance.",
    "A dramatic success prefers a patient build-up.",
    "The audience would like you to continue.",
    "The best surprises arrive with fanfare.",
    "A bold choice earns a standing ovation.",
    "The next victory arrives fashionably late.",
    "Something overdue is finally making its move.",
    "Even your obstacles feel theatrical lately.",
    "A glorious overreaction may become inspiration.",
    "An unexpected ally enters stage left.",
    "Your comeback is gathering momentum.",
    "The plot is thickening in your favor.",
    "An ordinary day is preparing a grand reveal.",
    "The cosmos loves a dramatic pause.",
    "Today contains premium plot development.",
    "The next scene contains better dialogue.",
    "The finale is nowhere near yet.",
    "The universe has upgraded your storyline.",
    "A brave decision steals the scene.",
    "Fortune favors the theatrically persistent.",
    "A memorable moment is taking shape.",
    "The next page turns itself.",
    "Your story refuses to be boring.",
    "Your resilience deserves better lighting.",
    "Something ordinary is about to feel legendary.",
    "A breakthrough is practicing its entrance.",
    "The narrative arc is improving rapidly.",
    "The stakes are lower than they seem but the drama is excellent.",
    "A triumph is approaching in slow motion.",
  ],
};

/**
 * Draw n unique fortunes from the specified vibe pool.
 * Wildcard draws across all four pools.
 *
 * @param {string} vibe — 'Mystical' | 'Funny' | 'Wholesome' | 'Dramatic' | 'Wildcard'
 * @param {number} n — number of fortunes to draw (default 8)
 * @returns {string[]} — array of n unique fortune strings
 */
export function pickFortunes(vibe, n = 8) {
  const pool = vibe === 'Wildcard'
    ? Object.values(FORTUNES).flat()
    : FORTUNES[vibe] ?? [];

  if (pool.length < n) {
    console.warn(`Fortune pool for "${vibe}" has fewer than ${n} entries.`);
  }

  const shuffled = [...pool].sort(() => Math.random() - 0.5);
  return shuffled.slice(0, n);
}

export { FORTUNES };
